-- public.posts table
CREATE TABLE public.bot_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  processed BOOLEAN DEFAULT FALSE NOT NULL
);

-- Comments for clarity
COMMENT ON TABLE public.posts IS 'Stores the queued posts for bot processing';